[theme]
primaryColor = 'rgb(234, 88, 12)'
backgroundColor = 'rgb(255, 250, 245)'
secondaryBackgroundColor = 'rgb(255, 243, 234)'
textColor = 'rgb(30, 41, 59)'
font = "sans serif"

[server]
maxUploadSize = 200
enableXsrfProtection = true
headless = true

[browser]
gatherUsageStats = false
